---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - '/'
      - '/.github/actions/*'
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    labels:
      - automation
      - skip-changelog
      - backport-active-all
    open-pull-requests-limit: 10
