# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:

steps:
  - label: "check-ci"
    key: "check-ci"
    command: "echo 'CI is running'"